database:
  host: 'host'
  port: '3306'
  database: 'db'
  username: 'user'
  password: 'pass'
  options: '?autoReconnect=true'

autoCacheReloader:
  enabled: true
  ticksBetween: 36000

repScoring:
  defaultRep: 5
  maxRep: 10
  minRep: 0
  maxModifier: 10
  minModifier: -10

# Run commands when a player join the server.
logicCommandEntries:
  enabled: false
  # leftOperand: trueAvg, shownAvg
  # Operator: ==, !=, >, >=, <, <=
  # rightOperand: a double
  # command: can include <player>, <trueAvg>, and <shownAvg>
  '1':
    enabled: true
    leftOperand: "shownAvg"
    operator: "=="
    rightOperand: 5.0
    command: "say <player>'s rep avg is equal to 5.0!"
  '2':
    enabled: true
    leftOperand: "shownAvg"
    operator: "!="
    rightOperand: 5.0
    command: "say <player>'s rep avg is not equal to 5.0!"
  '3':
    enabled: true
    leftOperand: "trueAvg"
    operator: ">"
    rightOperand: 2.0
    command: "say <player>'s actual rep avg is greater than 2!"
  '4':
    enabled: true
    leftOperand: "trueAvg"
    operator: "<="
    rightOperand: 2.0
    command: "say <player>'s actual rep avg is less than (or equal to) 2!"
  # Add more entries as needed

  # * These are example command entries; MC64 doesn't expose players'
  #   true rep avg, only the shown rep avg.