# MySQL
database:
  host: 'host'
  port: '3306'
  database: 'db'
  username: 'user'
  password: 'pass'
  options: '?autoReconnect=true'

# 20 ticks = 1 second
autoCacheReloader:
  enabled: true
  ticksBetween: 36000