database:
  host: 'host'
  port: '3306'
  database: 'db'
  username: 'user'
  password: 'pass'
  options: '?autoReconnect=true'

autoCacheReloader:
  enabled: true
  ticksBetween: 36000

repScoring:
  defaultRep: 5
  maxRep: 10
  minRep: 0
  maxModifier: 10
  minModifier: -10