# Rep64 v1.2.3 by @tbm00
# https://github.com/tbm00/Rep64

mysql:
  host: 'host'
  port: 3306
  database: 'db'
  username: 'user'
  password: 'pass'
  useSSL: false
  hikari:
    maximumPoolSize: 16
    minimumPoolSize: 2
    idleTimeout: 240 # 4 minutes
    connectionTimeout: 30 # 30 seconds
    maxLifetime: 1800 # 30 minutes
    leakDetection:
      enabled: false
      threshold: 2 # 2 seconds

autoCacheReloader:
  enabled: true
  ticksBetween: 36000

# Notch's trueAvg = average(rep scores set on Notch by other players)
# Notch's shownAvg = trueAvg + repModifier
# repModifier defaults to 0 & gets applied by staff with `/repadmin mod Notch #`
repScoring:
  # default rep score when a player first joins
  defaultRep: 5
  # maximum rep score a player can give someone else
  maxRep: 10
  # minimum rep score a player can give someone else
  minRep: 0
  # minimum modifier staff can give a player
  maxModifier: 10
  # minimum modifier staff can give a player
  minModifier: -10

# Run commands when a player join the server.
# These are just examples and should be modified.
logicCommandEntries:
  enabled: false
  # leftOperand: trueAvg, shownAvg
  # Operator: ==, !=, >, >=, <, <=
  # rightOperand: a double
  # command: can include <player>, <trueAvg>, and <shownAvg>
  '1':
    enabled: true
    leftOperand: "shownAvg"
    operator: "=="
    rightOperand: 5.0
    command: "say <player>'s rep avg is equal to 5.0!"
  '2':
    enabled: true
    leftOperand: "shownAvg"
    operator: "!="
    rightOperand: 5.0
    command: "say <player>'s rep avg is not equal to 5.0!"
  '3':
    enabled: true
    leftOperand: "trueAvg"
    operator: ">"
    rightOperand: 2.0
    command: "say <player>'s actual rep avg is greater than 2!"
  '4':
    enabled: true
    leftOperand: "trueAvg"
    operator: "<="
    rightOperand: 2.0
    command: "say <player>'s actual rep avg is less than (or equal to) 2!"
  # Add more entries as needed