name: Rep64
version: ${project.version}
description: This plugin enables player to give other players a reputation score
author: tbm00
main: dev.tbm00.spigot.rep64.Rep64
softdepend: [PlaceholderAPI]
api-version: 1.17
commands:
  rep:
    description: Give and display player reputations
  repadmin:
    description: Set reputation modifier + more
permissions:
  rep64.admin:
    description: Ability to use admin rep command
    default: op
  rep64.set.self:
    description: Ability to give yourself a rep score
    default: op
  rep64.set:
    description: Ability to give someone a rep score
    default: true
  rep64.show:
    description: Ability to view your average reputation
    default: true
  rep64.show.others:
    description: Ability to view others' average reputation
    default: true